services:
  postgres:
    container_name: postgres-phishing-validator
    image: postgres
    environment:
      POSTGRES_USER: phishing-validator
      POSTGRES_PASSWORD: phishing-validator
      PGDATA: /postgres_data
    volumes:
      - postgres:/postgres_data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin-phishing-validator
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-phishing-validator@test.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-phishing-validator}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
