spring:
  application:
    name: phishing-validator
  datasource:
    username: 'phishing-validator'
    password: 'phishing-validator'
    url: jdbc:h2:mem:phishing-validator
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
springdoc:
  swagger-ui:
    path: /swagger.html
  api-docs:
    path: /api-docs

phishing-validator:
  service:
    phone-number: 22123123999
    start: START
    stop: STOP

logging:
  level:
    pl.jakubdrozdz: DEBUG